### ISSUE TITLE
connect timeout error

### ISSUE THREAD

**Issue by ten51x** [clairelovesgravy/discord-bot-gemini#2]
我确保按照文档配置了bot，.env文件的配置是正确的，node.js版本为v20.10.0，后台开了全局VPN。

在运行后几秒钟，发生了timeout报错。

以下是我的报错信息：
`[nodemon] starting `node index.js`
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\GithubProgram\discord-bot-gemini\node_modules\undici\lib\core\connect.js:186:24)
    at D:\GithubProgram\discord-bot-gemini\node_modules\undici\lib\core\connect.js:133:46
    at Immediate._onImmediate (D:\GithubProgram\discord-bot-gemini\node_modules\undici\lib\core\connect.js:172:33)
    at process.processImmediate (node:internal/timers:478:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}

Node.js v20.10.0
`

感谢解答！

**Comment by clairelovesgravy** [comment]
usually in this case, you need to change your vpn route. gemini对网络的要求可比chatgpt还要高，在aws部署都说我有连接问题😊

**Comment by AlanBacker** [comment]
> usually in this case, you need to change your vpn route. gemini对网络的要求可比chatgpt还要高，在aws部署都说我有连接问题😊

套个Warp就行啦
