### ISSUE TITLE
这是怎么回事，告诉我怎么解决

### ISSUE THREAD

**Issue by MarchBeta2087** [clairelovesgravy/discord-bot-gemini#4]
GoogleGenerativeAIError: [400 Bad Request] User location is not supported for the API use.
    at makeRequest (D:\discord-bot-gemini-main\node_modules\@google\generative-ai\dist\index.js:207:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (D:\discord-bot-gemini-main\node_modules\@google\generative-ai\dist\index.js:511:22)
    at async runGeminiPro (D:\discord-bot-gemini-main\gemini.js:13:18)
    at async Client.<anonymous> (D:\discord-bot-gemini-main\index.js:128:28)

**Comment by clairelovesgravy** [comment]
User location is not supported for the API use.
pls switch your VPN location
